### PR TITLE
Self-signed SSL cert generation for development testing

### PR DESCRIPTION
**Pull request by andrewazores**

### CODE REVIEW

**Comment by vic-ma** [comment]
Do you want me to review this now, since it's marked as draft?

**Comment by vic-ma** [comment]
I seem to be getting `502` "Target SSL Untrusted" when using handlers that require JMX auth.

**Comment by andrewazores** [comment]
If you edit `generate-dev-certs.sh` and remove the `rm` on the last line, then copy `certs/server.ser` into `truststore`, does that fix the problem?

**Comment by vic-ma** [comment]
Yes that fixes it.

**Review by vic-ma — APPROVED** [review]

**Pull request merged**
