### PR TITLE
Remove String.format from logger calls to improve performance

### LINKED ISSUE #358: Don't use String.format inside log statements
See also https://github.com/rh-jmc-team/container-jfr-core/issues/52
See http://www.slf4j.org/faq.html#logging_performance

### PR DESCRIPTION
**Pull request by Alexjsenn**
Fixes #358 
There are two or three statements where I left the String.format call because they had several arguments, and it probably doesn't make sense to create functions for that exact number of objects in cjfr-core.

### CODE REVIEW

**Comment by andrewazores** [comment]
> they had several arguments, and it probably doesn't make sense to create functions for that exact number of objects in cjfr-core.

[varargs](https://docs.oracle.com/javase/8/docs/technotes/guides/language/varargs.html)?

**Comment by Alexjsenn** [comment]
> > they had several arguments, and it probably doesn't make sense to create functions for that exact number of objects in cjfr-core.
> 
> [varargs](https://docs.oracle.com/javase/8/docs/technotes/guides/language/varargs.html)? I believe the documentation specifies that this is how SLF4J does it - there are `logger.log(String msg)`, `logger.log(String msg, Object a)`, `logger.log(String msg, Object a, Object b)`, and `logger.log(String msg, Object... args)` methods defined. We can do the same.

Should I add these methods for all of the logger message types even though some may not be used?

**Comment by andrewazores** [comment]
They may not be used _right now_... IMO it only makes sense to make all of them consistent that way.

**Comment by Alexjsenn** [comment]
yes, it makes sense, I added all the methods in cjfr-core, and changed the last string.format calls.

**Comment by andrewazores** [comment]
Looks good. I manually rebased this and tested it myself and everything seems to continue working as expected. Please rebase this PR and I'll merge it.

**Review by andrewazores — APPROVED** [review]

**Pull request merged**
