### PR TITLE
[autorules] Rules POST handler enhancements

### PR DESCRIPTION
**Pull request by andrewazores**
This addresses previous review commentary for `POST /api/v2/rules` in #416.

### CODE REVIEW

**Comment by vic-ma** [comment]
I'm getting a unit test failure:

```
[ERROR] Failures: 
[ERROR] com.redhat.rhjmc.containerjfr.net.web.http.api.v2.RulesPostHandlerTest$Requests.throwsIfRequiredFormAttributesBlank(String,String,String)
[ERROR]   Run 1: RulesPostHandlerTest$Requests.throwsIfRequiredFormAttributesBlank:201 Unexpected exception type thrown ==> expected: <java.lang.NullPointerException> but was: <java.lang.IllegalArgumentException>
[ERROR]   Run 2: RulesPostHandlerTest$Requests.throwsIfRequiredFormAttributesBlank:201 Unexpected exception type thrown ==> expected: <java.lang.NullPointerException> but was: <java.lang.IllegalArgumentException>
[ERROR]   Run 3: RulesPostHandlerTest$Requests.throwsIfRequiredFormAttributesBlank:201 Unexpected exception type thrown ==> expected: <java.lang.NullPointerException> but was: <java.lang.IllegalArgumentException>
```

**Comment by andrewazores** [comment]
This is ready for re-review when you have time.

**Comment by vic-ma** [comment]
The response from trying to add a rule with a duplicate name is:
```
{"meta":{"type":"text/plain","status":"Internal Server Error"},"data":{"reason":"IOException occurred while writing rule definition"}}
```

The logs have more details, but maybe when rethrowing the `IOException` as an `ApiException`, it could just append the message from the `IOException`? For example:
```
{"meta":{"type":"text/plain","status":"Internal Server Error"},"data":{"reason":"IOException occurred while writing rule definition: Rule with name "foo" already exists; refusing to overwrite"}}
```

**Comment by andrewazores** [comment]
Sure, I'll do that. That's a good observation about the behaviour of `ApiExceptions` and how the `WebServer` emits responses for them - this is probably a more general problem to come back to as well.

**Review by vic-ma — APPROVED** [review]

**Pull request merged**
