### PR TITLE
Malformed WebSocket message handling

### LINKED ISSUE #109: Uncaught NPE when sent an empty websocket message with auth
Using websockat to connect to ws://localhost:8181/command if I press enter, inputting an empty string (I assume), there is an uncaught exception that makes the Websocket stuff die and no further action can be taken without restarting the server.
```
Exception in thread "main" java.lang.NullPointerException
        at com.redhat.rhjmc.containerjfr.tui.ws.WsCommandExecutor.run(WsCommandExecutor.java:50)
        at com.redhat.rhjmc.containerjfr.ContainerJfr.main(ContainerJfr.java:69)
```

If incorrect input like "hi" is provided, the server continues after responding over the websocket with error details. That should also occur for an empty message.

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #109

### CODE REVIEW

**Comment by jiekang** [comment]
Spotless complained to me on build about the import formatting

**Comment by jiekang** [comment]
The text "null" also triggers the NPE for me. Funny...

**Comment by andrewazores** [comment]
... *shakes fist at gson*

**Comment by andrewazores** [comment]
@jiekang I think this is pretty well covered now with the latest round of commits. Would you mind re-reviewing?

**Pull request merged**
