### PR TITLE
Grafana health/configuration bugfixes

### LINKED ISSUE #277: Grafana configuration requires explicit port number broken in OpenShift
`GET /health` sees this in logs:

```
[ERROR] io.vertx.ext.web.handler.impl.HttpStatusException: Internal Server Error
Caused by: java.lang.IllegalArgumentException: port p must be in range 0 <= p <= 65535
	at io.vertx.core.impl.Arguments.requireInRange(Arguments.java:44)
	at io.vertx.core.net.impl.SocketAddressImpl.<init>(SocketAddressImpl.java:32)
	at io.vertx.core.net.SocketAddress.inetSocketAddress(SocketAddress.java:37)
	at io.vertx.core.http.impl.HttpClientImpl.createRequest(HttpClientImpl.java:1106)
	at io.vertx.core.http.impl.HttpClientImpl.createRequest(HttpClientImpl.java:1074)
	at io.vertx.core.http.impl.HttpClientImpl.request(HttpClientImpl.java:591)
	at io.vertx.ext.web.client.impl.HttpContext.handlePrepareRequest(HttpContext.java:344)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:288)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:275)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:272)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:282)
	at io.vertx.ext.web.client.impl.HttpContext.prepareRequest(HttpContext.java:168)
	at io.vertx.ext.web.client.impl.HttpRequestImpl.send(HttpRequestImpl.java:331)
	at io.vertx.ext.web.client.impl.HttpRequestImpl.send(HttpRequestImpl.java:301)
	at com.redhat.rhjmc.containerjfr.net.web.handlers.HealthGetHandler.checkUri(HealthGetHandler.java:129)
	at com.redhat.rhjmc.containerjfr.net.web.handlers.HealthGetHandler.handle(HealthGetHandler.java:102)
	at com.redhat.rhjmc.containerjfr.net.web.handlers.HealthGetHandler.handle(HealthGetHandler.java:63)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

`oc describe` snippet:

```
    Environment:
      CONTAINER_JFR_PLATFORM:             com.redhat.rhjmc.containerjfr.platform.openshift.OpenShiftPlatformStrategy
      CONTAINER_JFR_SSL_PROXIED:          true
      CONTAINER_JFR_ALLOW_UNTRUSTED_SSL:  true
      CONTAINER_JFR_WEB_PORT:             8181
      CONTAINER_JFR_EXT_WEB_PORT:         443
      CONTAINER_JFR_WEB_HOST:             containerjfr-default.apps-crc.testing
      CONTAINER_JFR_LISTEN_PORT:          9090
      CONTAINER_JFR_EXT_LISTEN_PORT:      443
      CONTAINER_JFR_LISTEN_HOST:          containerjfr-command-default.apps-crc.testing
      GRAFANA_DASHBOARD_URL:              https://containerjfr-grafana-default.apps-crc.testing
      GRAFANA_DATASOURCE_URL:             http://172.25.131.63:8080
      CONTAINER_JFR_DISABLE_JMX_AUTH:     true
      CONTAINER_JFR_DISABLE_SSL:          true
```

The problematic execution pointed to by the stack trace appears to be (`HealthGetHandler.java`):

```
        checkUri(GRAFANA_DASHBOARD_ENV, "/api/health", dashboardAvailable);

    private void checkUri(String envName, String path, CompletableFuture<Boolean> future) {
        if (this.env.hasEnv(envName)) {
            URI uri;
            try {
                uri = new URI(this.env.getEnv(envName));
            } catch (URISyntaxException e) {
                logger.warn(e);
                future.complete(false);
                return;
            }
            webClient
                    .get(uri.getPort(), uri.getHost(), path)
                    .ssl("https".equals(uri.getScheme()))
                    .timeout(5000)
                    .send(
                            handler -> {
                                if (handler.failed()) {
                                    future.complete(false);
                                    this.logger.info(new IOException(handler.cause()));
                                    return;
                                }
                                future.complete(handler.result().statusCode() == 200);
                            });
        } else {
            future.complete(false);
        }
    }

```

I think, from a reading, that the problem is that the `uri` is `https://containerjfr-grafana-default.apps-crc.testing`, which has no explicit port number, so `uri.getPort()` is `-1` and the request send fails.

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #277 and #279

### CODE REVIEW

**Comment by vic-ma** [comment]
I was able to push the operator image to quay successfully since my internet speed is better now, but I'm running into issues with `make deploy`:
```
[vma@victor-work ~/container-jfr-operator]$ make deploy
oc delete all -l app=vertx-fib-demo
No resources found
oc delete all -l app=jmx-listener
No resources found
oc delete recording --all
error: the server doesn't have a resource type "recording"
make: [Makefile:140: undeploy] Error 1 (ignored)
oc delete flightrecorder --all
error: the server doesn't have a resource type "flightrecorder"
make: [Makefile:141: undeploy] Error 1 (ignored)
oc delete containerjfr --all
error: the server doesn't have a resource type "containerjfr"
make: [Makefile:142: undeploy] Error 1 (ignored)
oc delete deployment container-jfr-operator
Error from server (NotFound): deployments.apps "container-jfr-operator" not found
make: [Makefile:143: undeploy] Error 1 (ignored)
oc delete all -l name=container-jfr-operator
No resources found
oc delete all -l app=containerjfr
No resources found
oc delete persistentvolumeclaims -l app=containerjfr
No resources found
oc delete persistentvolumes -l app=containerjfr
No resources found
oc delete configmaps -l app=containerjfr
No resources found
oc delete role container-jfr-operator
Error from server (NotFound): roles.rbac.authorization.k8s.io "container-jfr-operator" not found
make: [Makefile:149: undeploy] Error 1 (ignored)
oc delete rolebinding container-jfr-operator
Error from server (NotFound): rolebindings.rbac.authorization.k8s.io "container-jfr-operator" not found
make: [Makefile:150: undeploy] Error 1 (ignored)
oc delete serviceaccount container-jfr-operator
Error from server (NotFound): serviceaccounts "container-jfr-operator" not found
make: [Makefile:151: undeploy] Error 1 (ignored)
oc delete crd flightrecorders.rhjmc.redhat.com
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "flightrecorders.rhjmc.redhat.com" not found
make: [Makefile:152: undeploy] Error 1 (ignored)
oc delete crd recordings.rhjmc.redhat.com
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "recordings.rhjmc.redhat.com" not found
make: [Makefile:153: undeploy] Error 1 (ignored)
oc delete crd containerjfrs.rhjmc.redhat.com
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "containerjfrs.rhjmc.redhat.com" not found
make: [Makefile:154: undeploy] Error 1 (ignored)
oc delete -f deploy/olm-catalog/catalog-source.yaml
Error from server (NotFound): error when deleting "deploy/olm-catalog/catalog-source.yaml": catalogsources.operators.coreos.com "rh-jmc-team-manifests" not found
make: [Makefile:155: undeploy] Error 1 (ignored)
oc create -f deploy/service_account.yaml
serviceaccount/container-jfr-operator created
oc create -f deploy/role.yaml
role.rbac.authorization.k8s.io/container-jfr-operator created
oc create -f deploy/role_binding.yaml
rolebinding.rbac.authorization.k8s.io/container-jfr-operator created
oc create -f deploy/crds/rhjmc.redhat.com_flightrecorders_crd.yaml
customresourcedefinition.apiextensions.k8s.io/flightrecorders.rhjmc.redhat.com created
oc create -f deploy/crds/rhjmc.redhat.com_recordings_crd.yaml
customresourcedefinition.apiextensions.k8s.io/recordings.rhjmc.redhat.com created
oc create -f deploy/crds/rhjmc.redhat.com_containerjfrs_crd.yaml
customresourcedefinition.apiextensions.k8s.io/containerjfrs.rhjmc.redhat.com created
sed -e 's|REPLACE_IMAGE|quay.io/vic_ma/container-jfr-operator|g' deploy/dev_operator.yaml | oc create -f -
deployment.apps/container-jfr-operator created
oc set env deployment/container-jfr-operator TLS_VERIFY=false
deployment.apps/container-jfr-operator updated
oc create -f deploy/crds/rhjmc.redhat.com_v1alpha1_containerjfr_cr.yaml
containerjfr.rhjmc.redhat.com/containerjfr created
```
```
[vma@victor-work ~/container-jfr-operator]$ oc get pod
NAME                                      READY   STATUS         RESTARTS   AGE
container-jfr-operator-84f488986d-bpfk4   0/1     ErrImagePull   0          111s
```

**Comment by andrewazores** [comment]
What do you have the environment variables `IMAGE_STREAM`/`IMAGE_VERSION`/`IMAGE_TAG` set to, if anything? Is your image repository on quay.io public or private? What is the error state given by `oc describe pod container-jfr-operator-84f488986d-bpfk4`?

**Comment by vic-ma** [comment]
Ah, yes it was private. I changed it to public and now I'm able to create a recording, so I think it's working.

**Comment by andrewazores** [comment]
Nice. With this fix applied in the container-jfr image there should be no error notification about the Grafana configuration, and the "View in Grafana..." menu item should appear in the recording list actions. Clicking it should eventually produce an "Upload succeeded" notification and bring you to the Grafana dashboard, although that may not be configured so the data may not be presented to you right away (rh-jmc-team/container-jfr-operator#112).

**Comment by vic-ma** [comment]
How do I use this fix with the operator image? I tried just building this cjfr image and then rebuilding/pushing the operator image but I'm guessing that isn't the way to do it or there's a step I'm missing.

**Comment by andrewazores** [comment]
You would have to edit `resource_definitions.go` in the Operator, there's a line in there that defines the image tag for the ContainerJFR container that the Operator deploys. Just change that line to point to your custom image, then rebuild/push/deploy your customized Operator image.

**Comment by vic-ma** [comment]
So in the pom of container-jfr I made this change:
```
-  <containerjfr.imageStream>quay.io/rh-jmc-team/container-jfr</containerjfr.imageStream>
+  <containerjfr.imageStream>quay.io/vic_ma/container-jfr</containerjfr.imageStream>
```

And then I built the image, and did `podman image push quay.io/vic_ma/container-jfr`, and then in the operator I made this change:
```
-       imageTag := "quay.io/rh-jmc-team/container-jfr:0.20.0"
+       imageTag := "quay.io/vic_ma/container-jfr:0.20.0"
```

And then in the operator repo I did `make clean image && podman image push $IMAGE_TAG && make deploy`, but the cjfr image is not being pulled properly:
```
NAME                                      READY   STATUS             RESTARTS   AGE
container-jfr-operator-84f488986d-qj6km   1/1     Running            0          8m8s
containerjfr-685958df6d-6rbcs             2/3     ImagePullBackOff   0          7m31s
```
```
Events:
  Type     Reason          Age                    From                         Message
  ----     ------          ----                   ----                         -------
  Normal   Scheduled       8m6s                   default-scheduler            Successfully assigned default/containerjfr-685958df6d-6rbcs to crc-zqfk6-master-0
  Normal   AddedInterface  8m4s                   multus                       Add eth0 [10.116.0.62/23]
  Normal   Pulled          8m4s                   kubelet, crc-zqfk6-master-0  Container image "docker.io/grafana/grafana:6.4.4" already present on machine
  Normal   Started         8m3s                   kubelet, crc-zqfk6-master-0  Started container containerjfr-jfr-datasource
  Normal   Created         8m3s                   kubelet, crc-zqfk6-master-0  Created container containerjfr-jfr-datasource
  Normal   Pulled          8m3s                   kubelet, crc-zqfk6-master-0  Container image "quay.io/rh-jmc-team/jfr-datasource:0.0.1" already present on machine
  Normal   Started         8m3s                   kubelet, crc-zqfk6-master-0  Started container containerjfr-grafana
  Normal   Created         8m3s                   kubelet, crc-zqfk6-master-0  Created container containerjfr-grafana
  Warning  Failed          7m22s (x3 over 8m4s)   kubelet, crc-zqfk6-master-0  Error: ErrImagePull
  Warning  Failed          7m22s (x3 over 8m4s)   kubelet, crc-zqfk6-master-0  Failed to pull image "quay.io/vic_ma/container-jfr:0.20.0": rpc error: code = Unknown desc = Error reading manifest 0.20.0 in quay.io/vic_ma/container-jfr: manifest unknown: manifest unknown
  Normal   Pulling         7m22s (x3 over 8m4s)   kubelet, crc-zqfk6-master-0  Pulling image "quay.io/vic_ma/container-jfr:0.20.0"
  Normal   BackOff         6m55s (x5 over 8m3s)   kubelet, crc-zqfk6-master-0  Back-off pulling image "quay.io/vic_ma/container-jfr:0.20.0"
  Warning  Failed          2m57s (x21 over 8m3s)  kubelet, crc-zqfk6-master-0  Error: ImagePullBackOff
```

But if I just run `podman pull quay.io/vic_ma/container-jfr`, it runs without any errors. And I set the repo to public.

I did also test changing the container-jfr image to be the one from your quay repo, and it works if I do that and I was able to verify the fix. But I'm not sure if it's important for me to test it using my own image.

**Comment by andrewazores** [comment]
Hmm. I'll see if I can reproduce that with my CRC instance tomorrow. I was just able to run your image and verify the fix is there with a simple `cd container-jfr; CONTAINER_JFR_IMAGE=quay.io/vic_ma/container-jfr:0.20.0 sh smoketest.sh` too, so I'm not sure why the Operator isn't able to deploy it.

Anyway, if you were at least able to verify it on the image I built, I suppose that's good enough. Ideally you would also be able to build and test your own images for verification as well, though.

**Review by vic-ma — APPROVED** [review]

**Comment by andrewazores** [comment]
@vic-ma hmm, I was able to deploy your container-jfr image in my operator just now by following the same procedure. Not sure why your cluster wasn't able to pull it before - what happens if you `crc delete` and start over?

**Comment by vic-ma** [comment]
Yes it seems to be working now...strange but good I guess.

**Pull request merged**
